#include<stdio.h>
int main(void){
  unsigned long long int i, A;
  int flag=0;
  scanf("%lld",&A);

  /*
  A=13;
  A_MAX=9223372036854775783;
  while(A<9223372036854775785){
  flag=0;
  */

  if(A % 2 == 0){ printf("Not Prime.\n"); return 0; }
  if(A % 3 == 0){ printf("Not Prime.\n"); return 0; }
  if(A % 5 == 0){ printf("Not Prime.\n"); return 0; }
  if(A % 7 == 0){ printf("Not Prime.\n"); return 0; }
  if(A %11 == 0){ printf("Not Prime.\n"); return 0; }
  //printf("1\n");

  /*
  if(A % 2 == 0) flag++;
  if(A % 3 == 0) flag++;
  if(A % 5 == 0) flag++;
  if(A % 7 == 0) flag++;
  if(A %11 == 0) flag++;
  */

  //  if(i*i>A) break;

  for(i=13;i*i<A+1&&flag==0;){
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=20;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=22;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=34;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=20;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=24;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=16;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=16;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=22;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=14;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=16;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=10;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=18;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=24;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=16;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=16;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=8;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=6;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=4;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=12;
    if(i*i>A+1) break;
    if(A%i==0) flag++;
    i+=2;
    if(i*i>A+1) break;
    if(A%i==0)flag++;
    i+=22;
  }

  /*
  if(flag==0) printf("%lld ",A);
  A++;
  }
  printf("\n");
  */

  if(flag==0){ 
    printf("Prime.\n");
  }else{
    printf("Not Prime.\n");
  }

  return 0;
}
